CREATE TABLE `USR_CUSTOMER_PROFILE` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `full_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `mobile_no` VARCHAR(20) NULL,
  `address` VARCHAR(100) NULL,
  `postal_code` VARCHAR(10) NULL,
  `city` VARCHAR(30) NULL,
  `state` VARCHAR(30) NULL,
  `country` VARCHAR(30) NULL,
  `identity_no` VARCHAR(20) NULL,
  `status` VARCHAR(20) NULL,
  `pending_status` VARCHAR(20) NULL,
  `tmp_full_name` VARCHAR(100) NULL,
  `tmp_email` VARCHAR(100) NULL,
  `tmp_mobile_no` VARCHAR(20) NULL,
  `tmp_address` VARCHAR(100) NULL,
  `tmp_postal_code` VARCHAR(10) NULL,
  `tmp_city` VARCHAR(30) NULL,
  `tmp_state` VARCHAR(30) NULL,
  `tmp_country` VARCHAR(30) NULL,
  `tmp_identity_no` VARCHAR(20) NULL,
  `date_created` DATETIME NOT NULL,
  `created_by` VARCHAR(50) NOT NULL,
  `last_updated` DATETIME NOT NULL,
  `updated_by` VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
